# ============================================================
# ui.R -- UI builder for scTAMsExplorer
# ============================================================

#' Build a feature card for the About page
#'
#' Internal layout helper. Renders a small card with an icon,
#' a title and a bullet list of features.
#'
#' @param icon Character or HTML. Icon (typically an HTML entity).
#' @param title Character. Card heading.
#' @param items Character vector of bullet items.
#'
#' @return A `shiny::tags$div`.
#'
#' @importFrom shiny tags
#'
#' @keywords internal
#' @noRd
.feature_card <- function(icon, title, items) {
  shiny::tags$div(class = "feature-card",
    shiny::tags$div(class = "fc-icon", icon),
    shiny::tags$h3(title),
    shiny::tags$ul(lapply(items, function(i) shiny::tags$li(i)))
  )
}

#' Render an icon-prefixed tab label
#'
#' Internal helper to combine an HTML icon and a text label
#' into a single `shiny::HTML` blob suitable for `tabPanel()`.
#'
#' @param icon_html Character. Raw HTML for the icon
#'   (typically an entity such as `"&#8505;"`).
#' @param text Character. Visible tab label.
#'
#' @return A `shiny::HTML` object.
#'
#' @importFrom shiny HTML
#'
#' @keywords internal
#' @noRd
.tab_label <- function(icon_html, text) {
  shiny::HTML(paste0('<span class="tab-icon">', icon_html, "</span>", text))
}

#' Build the Shiny UI for the Atlas Explorer
#'
#' Constructs the dashboard UI with five main tabs (UMAP +
#' Expression, DEGs + Volcano + Enrichment, TF Network,
#' Co-expression Modules, TF Regulon Heatmap) plus an About
#' landing page. All input widgets are populated from the
#' supplied `metadata_choices`.
#'
#' This function is not exported: end users build the app via
#' [launch_explorer()].
#'
#' @param metadata_choices Character vector of metadata column
#'   names returned by [get_metadata_choices()].
#'
#' @return A Shiny UI definition (a `fluidPage` object).
#'
#' @section CSS:
#' The UI calls `app_css()` to inject the dashboard stylesheet.
#' That helper is defined elsewhere in the package (see e.g.
#' `R/css.R`). Make sure it is available at load time.
#'
#' @importFrom shiny fluidPage tags HTML tabsetPanel tabPanel
#' @importFrom shiny sidebarLayout sidebarPanel mainPanel
#' @importFrom shiny fluidRow column h4 h5 hr br
#' @importFrom shiny selectInput numericInput textInput sliderInput
#' @importFrom shiny checkboxInput radioButtons actionButton
#' @importFrom shiny conditionalPanel icon
#' @importFrom shiny downloadButton uiOutput textOutput plotOutput
#' @importFrom shiny verbatimTextOutput helpText
#' @importFrom DT DTOutput
#' @importFrom plotly plotlyOutput
#' @importFrom visNetwork visNetworkOutput
#'
#' @keywords internal
atlas_ui <- function(metadata_choices) {

  shiny::fluidPage(
    shiny::tags$head(shiny::tags$style(shiny::HTML(app_css()))),

    shiny::tags$div(class = "app-header",
      shiny::tags$span(class = "app-icon",
                       shiny::HTML("&#129516;")),
      shiny::tags$div(
        shiny::tags$h1("scTAMsExplorer"),
        shiny::tags$p(class = "app-subtitle",
                      "Single-cell RNA-seq analysis - Interactive dashboard")
      )
    ),

    shiny::tags$div(class = "nav-wrapper",
      shiny::tabsetPanel(id = "main_tabs",

        # ---- Tab 0: About ------------------------------------------
        shiny::tabPanel(.tab_label("&#8505;", "About"),
          shiny::tags$div(
            style = "max-width:2000px;margin:0 auto;padding:22px 12px 0;",

            shiny::tags$div(class = "info-hero",
              shiny::tags$span(class = "hero-badge",
                               "Bioinformatics - scRNA-seq - Single-cell Atlas"),
              shiny::tags$h2("Welcome to scTAMsExplorer"),
              shiny::tags$p(
                "A modular, interactive dashboard for exploring single-cell RNA-seq atlases.",
                "All computations run live on the Seurat object passed to ",
                shiny::tags$code("launch_explorer()"), "."
              )
            ),

            shiny::tags$div(class = "info-tip",
              shiny::tags$strong("How to use: "),
              "Select any tab above. Set parameters in the left sidebar and press the action",
              "button. All results can be downloaded as PNG or CSV."
            ),

            shiny::tags$div(class = "dataset-block",
              shiny::tags$h3("About this dataset"),
              shiny::tags$p(
                "This atlas was generated by the ",
                shiny::tags$strong("Goriely Lab"),
                " and comprises single-cell transcriptomic profiles spanning multiple",
                " cell populations and tissue compartments. Cells were sequenced using",
                " 10x Genomics Chromium technology, aligned with Cell Ranger, and processed",
                " in Seurat with Harmony-based batch correction for cross-sample integration."
              ),
              shiny::tags$p(
                "Dimensionality reduction: PCA + UMAP on the Harmony-corrected embedding",
                " (", shiny::tags$code("umap.harmony"), ").",
                " Cell-type annotation at multiple resolution levels (Population_level1-3).",
                " TF activity inferred via GRN; co-expression modules identified with hdWGCNA."
              ),
              shiny::tags$div(class = "ds-meta",
                lapply(
                  c("10x Genomics Chromium", "Harmony integration",
                    "Multi-level annotation", "TF regulon analysis",
                    "hdWGCNA modules", "EnrichR pathway analysis"),
                  function(t) shiny::tags$span(class = "ds-tag", t)
                )
              )
            ),

            shiny::tags$div(class = "feature-grid",
              .feature_card(shiny::HTML("&#128506;"), "UMAP + Expression", list(
                "UMAP coloured by any metadata column",
                "FeaturePlot, VlnPlot, DotPlot, DoHeatmap",
                "Blend mode: co-expression of two genes",
                "Split violin / feature plot by any metadata",
                "Top marker genes per cluster (FindMarkers)",
                "Adjustable display size, font and DPI")),
              .feature_card(shiny::HTML("&#127755;"), "DEGs + Volcano + Enrichment", list(
                "Subset cells by any metadata value",
                "FindMarkers between any two groups",
                "Interactive volcano with ggrepel labels",
                "p-value and log2FC threshold sliders",
                "Enrichment run separately via EnrichR",
                "Full geneset tables, UP and DOWN CSVs")),
              .feature_card(shiny::HTML("&#127760;"), "TF Interaction Network", list(
                "Interactive drag-and-zoom visNetwork graph",
                "5 layout algorithms to choose from",
                "Filter by Gain threshold and top N targets",
                "Reverse search: find TFs regulating a gene",
                "TF-TF only interaction mode",
                "Full DB or filtered network CSV download")),
              .feature_card(shiny::HTML("&#128279;"), "Co-expression Modules", list(
                "hdWGCNA hub gene tables (ranked by kME)",
                "Module size overview table",
                "Gene to Module lookup by gene name",
                "Per-module pathway enrichment (EnrichR)",
                "Sortable, filterable, paginated tables")),
              .feature_card(shiny::HTML("&#127919;"), "TF Regulon Heatmap", list(
                "Dot heatmap: TF expression vs regulon activity",
                "Side-by-side positive and negative regulons",
                "Filter by module membership or manual TF list",
                "Per-TF EnrichR enrichment (pos & neg)",
                "PNG heatmap and data CSV download")),
              .feature_card(shiny::HTML("&#9881;"), "Universal plot controls", list(
                "Per-plot pixel size sliders for display",
                "Separate inch + DPI controls for download",
                "Font / label size slider on every plot",
                "All tables: sortable, filterable, paginated",
                "All results: PNG and CSV download buttons"))
            ),

            shiny::tags$div(class = "card",
              shiny::tags$div(class = "card-title", "Required R packages"),
              shiny::tags$div(class = "tech-pills",
                lapply(
                  c("Seurat","ggplot2","dplyr","tidyr","plotly","DT",
                    "enrichR","patchwork","ggrepel","visNetwork",
                    "scales","stringr","tibble","hdWGCNA"),
                  function(p) shiny::tags$span(class = "tech-pill", p)
                )
              )
            ),

            shiny::tags$div(class = "info-footer",
              shiny::tags$div(class = "footer-credit",
                shiny::tags$strong("Goriely Lab"), shiny::tags$br(),
                "Institute of Medical Immunology (IMI) - University of Brussels (ULB)",
                shiny::tags$br(),
                shiny::tags$span(style = "font-size:12px;color:#6b7f96;",
                  "Dataset and analysis pipeline developed by the Goriely Lab.")
              ),
              shiny::tags$span(class = "footer-badge", "Goriely Lab - ULB")
            ),
            shiny::tags$div(style = "height:30px;")
          )
        ),

        # ---- Tab 1: UMAP + Expression ------------------------------
        shiny::tabPanel(.tab_label("&#128506;", "UMAP"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("UMAP"),
              shiny::selectInput("umap_groupby", "Group by:",
                choices  = metadata_choices,
                selected = if ("Population_level3" %in% metadata_choices)
                  "Population_level3" else metadata_choices[1]),
              shiny::uiOutput("cluster_selector"),
              shiny::h4("Expression"),
              textInput("feature", "Gene / Feature:", value = "MS4A1"),
              actionButton("go_feature", "OK"),
              shiny::textInput("feature2", "Gene 2 (blend / heatmap / dot):",
                               value = "CD3D"),
              shiny::radioButtons("plot_type", "Plot type:",
                choices = c("FeaturePlot" = "feature", "VlnPlot" = "vln",
                            "DotPlot" = "dot", "Heatmap" = "heatmap")),
              shiny::conditionalPanel("input.plot_type == 'feature'",
                shiny::checkboxInput("blend_mode",
                  "Blend two genes (co-expression)", FALSE)),
              shiny::conditionalPanel(
                "input.plot_type == 'feature' || input.plot_type == 'vln'",
                shiny::checkboxInput("use_split", "Split by metadata", FALSE),
                shiny::conditionalPanel("input.use_split",
                  shiny::selectInput("split_by", "Split by:",
                    choices  = metadata_choices,
                    selected = if (length(metadata_choices) > 1)
                      metadata_choices[2] else metadata_choices[1])
                )
              ),
              shiny::h4("Marker genes"),
              shiny::sliderInput("n_markers", "Top markers:", min = 5, max = 100, value = 20),
              shiny::actionButton("markers", "Compute markers",
                icon = shiny::icon("dna"), class = "btn-primary"),
              shiny::h4("Plot controls"),
              plot_size_controls("umap", default_w = 720, default_h = 500),
              plot_size_controls("expr", default_w = 720, default_h = 500),
              shiny::hr(), shiny::h5("Downloads"),
              shiny::downloadButton("download_umap",      "UMAP PNG"),
              shiny::downloadButton("download_expr_plot", "Expression PNG"),
              shiny::downloadButton("download_markers",   "Markers CSV")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "UMAP"),
                shiny::uiOutput("umap_container")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "Expression plot"),
                shiny::uiOutput("expr_container")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "Marker genes"),
                DT::DTOutput("marker_table"))
            )
          )
        ),

        # ---- Tab 2: DEGs -------------------------------------------
        shiny::tabPanel(.tab_label("&#127755;", "DEGs"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Subset & compare"),
              shiny::selectInput("deg_subset_meta", "Subset by:",
                choices  = metadata_choices,
                selected = if ("Population_level3" %in% metadata_choices)
                  "Population_level3" else metadata_choices[1]),
              shiny::uiOutput("deg_subset_value_selector"), shiny::hr(),
              shiny::selectInput("deg_compare_meta", "Compare groups from:",
                choices  = metadata_choices,
                selected = if ("tissue" %in% metadata_choices)
                  "tissue" else metadata_choices[1]),
              shiny::uiOutput("deg_group1_selector"),
              shiny::uiOutput("deg_group2_selector"),
              shiny::h4("Thresholds"),
              shiny::sliderInput("pval_cut",    "Adj p-value cutoff:",
                min = 0.0001, max = 0.1,  value = 0.05),
              shiny::sliderInput("lfc_cut",     "|log2FC| cutoff:",
                min = 0,      max = 5,    value = 0, step = 0.1),
              shiny::sliderInput("n_label",     "Volcano labels:",
                min = 0,      max = 30,   value = 10),
              shiny::sliderInput("n_deg_table", "Rows in DEG table:",
                min = 10,     max = 500,  value = 100),
              shiny::actionButton("deg", "Run DEG analysis",
                icon = shiny::icon("calculator"), class = "btn-primary"),
              shiny::h4("Enrichment"),
              shiny::selectInput("enrich_db", "EnrichR database:",
                choices = c("GO_Biological_Process_2023",
                            "GO_Molecular_Function_2023",
                            "KEGG_2021_Human", "Reactome_2022")),
              shiny::sliderInput("n_enrich", "Top terms:", min = 5, max = 30, value = 15),
              shiny::actionButton("run_enrich", "Run Enrichment",
                icon = shiny::icon("chart-bar"), class = "btn-success"),
              shiny::h4("Plot controls"),
              plot_size_controls("volcano", default_w = 720, default_h = 540),
              plot_size_controls("enrich",  default_w = 720, default_h = 380),
              shiny::hr(), shiny::h5("Downloads"),
              shiny::downloadButton("download_degs",            "DEGs CSV"),
              shiny::downloadButton("download_volcano",         "Volcano PNG"),
              shiny::downloadButton("download_enrich_up",       "UP enrichment PNG"),
              shiny::downloadButton("download_enrich_down",     "DOWN enrichment PNG"),
              shiny::downloadButton("download_enrich_up_csv",   "UP enrichment CSV"),
              shiny::downloadButton("download_enrich_down_csv", "DOWN enrichment CSV")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "DEG results"),
                DT::DTOutput("deg_table")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "Volcano plot"),
                shiny::uiOutput("volcano_container")),
              shiny::fluidRow(
                shiny::column(6,
                  shiny::tags$div(class = "card",
                    shiny::tags$div(class = "card-title", "UP-regulated enrichment"),
                    shiny::plotOutput("enrich_up_plot"), shiny::hr(),
                    shiny::h5(style = "font-size:13px;color:#1a2e45;margin-top:10px;",
                              "Geneset table"),
                    DT::DTOutput("enrich_up_table"))),
                shiny::column(6,
                  shiny::tags$div(class = "card",
                    shiny::tags$div(class = "card-title", "DOWN-regulated enrichment"),
                    shiny::plotOutput("enrich_down_plot"), shiny::hr(),
                    shiny::h5(style = "font-size:13px;color:#1a2e45;margin-top:10px;",
                              "Geneset table"),
                    DT::DTOutput("enrich_down_table")))
              )
            )
          )
        ),

        # ---- Tab 3: TF Network -------------------------------------
        shiny::tabPanel(.tab_label("&#127760;", "TF Network"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Source TF"),
              shiny::textInput("tf_center", "TF (source):", "MAFB"),
              shiny::h4("Reverse search"),
              shiny::textInput("tf_target_search", "Find TFs regulating gene:", ""),
              shiny::h4("Filters"),
              shiny::sliderInput("min_gain",      "Min Gain:",
                min = 0, max = 1, value = 0.05, step = 0.01),
              shiny::sliderInput("n_top_targets", "Top N targets:",
                min = 5, max = 200, value = 50),
              shiny::radioButtons("target_level", "Depth:",
                choices = c("1-step" = 1, "2-step" = 2)),
              shiny::checkboxInput("tf_tf_only",
                "Show only TF-TF interactions", FALSE),
              shiny::h4("Layout"),
              shiny::selectInput("network_layout", "Algorithm:",
                choices = c(
                  "Fruchterman-Reingold" = "fr",
                  "Kamada-Kawai"         = "kk",
                  "Large graph (DrL)"    = "drl",
                  "Circle"               = "circle",
                  "Nicely"               = "nicely")),
              shiny::actionButton("update_network", "Update network",
                icon = shiny::icon("rotate"), class = "btn-primary"),
              shiny::hr(), shiny::h5("Downloads"),
              shiny::downloadButton("download_network_full",     "Full interaction DB (CSV)"),
              shiny::downloadButton("download_network_filtered", "Filtered network (CSV)")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "TF Interaction Network",
                  shiny::tags$span(
                    style = "font-size:11px;color:#8099b4;font-weight:400;margin-left:8px;",
                    "Blue diamond = TF | Grey dot = target | Red = center | Blue edge = pos | Red edge = neg"
                  )
                ),
                visNetwork::visNetworkOutput("network_plot", height = "680px")
              )
            )
          )
        ),

        # ---- Tab 4: Modules ----------------------------------------
        shiny::tabPanel(.tab_label("&#128279;", "Modules"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Hub genes"),
              shiny::sliderInput("coexp_n_hubs", "Top hub genes per module:",
                min = 5, max = 50, value = 10),
              shiny::actionButton("run_coexp", "Load modules",
                icon = shiny::icon("dna"), class = "btn-primary"),
              shiny::downloadButton("download_hub_genes", "Hub genes CSV"),
              shiny::h4("Gene lookup"),
              shiny::textInput("gene_lookup", "Gene name:", ""),
              shiny::actionButton("run_gene_lookup", "Find module",
                icon = shiny::icon("search"), class = "btn-primary"),
              shiny::h4("Module enrichment"),
              shiny::uiOutput("coexp_module_selector"),
              shiny::selectInput("coexp_enrich_db", "EnrichR database:",
                choices = c("GO_Biological_Process_2023",
                            "GO_Molecular_Function_2023",
                            "KEGG_2021_Human", "Reactome_2022")),
              shiny::sliderInput("coexp_n_enrich", "Top terms:",
                min = 5, max = 30, value = 10),
              shiny::actionButton("run_coexp_enrich", "Run enrichment",
                icon = shiny::icon("chart-bar"), class = "btn-success"),
              shiny::h4("Plot controls"),
              plot_size_controls("coexp_enrich", default_w = 720, default_h = 380),
              shiny::hr(),
              shiny::downloadButton("download_coexp_enrich",      "Enrichment CSV"),
              shiny::downloadButton("download_coexp_enrich_plot", "Barplot PNG")
            ),
            shiny::mainPanel(width = 9,
              shiny::fluidRow(
                shiny::column(5,
                  shiny::tags$div(class = "card",
                    shiny::tags$div(class = "card-title", "Module sizes"),
                    DT::DTOutput("module_size_table"))),
                shiny::column(7,
                  shiny::tags$div(class = "card",
                    shiny::tags$div(class = "card-title", "Gene to Module lookup"),
                    shiny::verbatimTextOutput("gene_lookup_result")))
              ),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "Hub genes per module"),
                DT::DTOutput("hub_genes_table")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title",
                  shiny::textOutput("enrich_module_title", inline = TRUE)),
                shiny::uiOutput("coexp_enrich_container"), shiny::hr(),
                DT::DTOutput("coexp_enrich_table"))
            )
          )
        ),

        # ---- Tab 5: Regulon ----------------------------------------
        shiny::tabPanel(.tab_label("&#127919;", "Regulon"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Heatmap settings"),
              shiny::h5("Module filter"),
              shiny::uiOutput("reg_module_selector"),
              shiny::helpText("Leave 'All modules' to show all TFs."),
              shiny::h5("Network filters"),
              shiny::sliderInput("reg_min_gain", "Min Gain:",
                min = 0, max = 1, value = 0.05, step = 0.01),
              shiny::sliderInput("reg_min_regulon_size",
                "Min regulon size (pos/neg):", min = 1, max = 50, value = 5),
              shiny::h5("Display"),
              shiny::sliderInput("reg_top_n_tfs",
                "Top N TFs (by regulon size):", min = 5, max = 100, value = 30),
              shiny::textInput("reg_tf_filter", "Manual TF filter (comma-sep):", ""),
              shiny::sliderInput("reg_dot_range", "Dot size range:",
                min = 0.5, max = 10, value = c(1, 7), step = 0.5),
              shiny::actionButton("run_reg_heatmap", "Build heatmap",
                icon = shiny::icon("fire"), class = "btn-primary"),
              shiny::h4("Plot controls"),
              plot_size_controls("reg", default_w = 820, default_h = 880),
              shiny::br(),
              shiny::downloadButton("download_reg_plot", "Heatmap PNG"),
              shiny::downloadButton("download_reg_csv",  "Data CSV"),
              shiny::h4("TF Regulon Enrichment"),
              shiny::helpText("Build the heatmap first, then select a TF."),
              shiny::uiOutput("reg_enrich_tf_selector"),
              shiny::selectInput("reg_enrich_db", "Database:",
                choices = c("GO_Biological_Process_2023",
                            "GO_Molecular_Function_2023",
                            "KEGG_2021_Human", "Reactome_2022")),
              shiny::sliderInput("reg_enrich_n", "Top terms:",
                min = 5, max = 30, value = 10),
              shiny::actionButton("run_reg_enrich", "Run enrichment",
                icon = shiny::icon("magnifying-glass"), class = "btn-success"),
              shiny::h4("Enrichment plot controls"),
              plot_size_controls("reg_enrich", default_w = 720, default_h = 430),
              shiny::br(),
              shiny::downloadButton("download_reg_enrich_pos_png", "POS enrichment PNG"),
              shiny::downloadButton("download_reg_enrich_neg_png", "NEG enrichment PNG"),
              shiny::downloadButton("download_reg_enrich_pos_csv", "POS enrichment CSV"),
              shiny::downloadButton("download_reg_enrich_neg_csv", "NEG enrichment CSV")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "Regulon dot heatmap"),
                shiny::textOutput("reg_status"), shiny::br(),
                shiny::uiOutput("reg_heatmap_container")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "Regulon summary"),
                DT::DTOutput("reg_summary_table")),
              shiny::fluidRow(
                shiny::column(6,
                  shiny::tags$div(class = "card",
                    shiny::tags$div(class = "card-title", "Positive regulon enrichment"),
                    shiny::helpText(style = "font-size:11px;color:#8099b4;",
                                    "Genes positively correlated (Cor > 0)"),
                    DT::DTOutput("reg_enrich_pos_table"),
                    shiny::uiOutput("reg_enrich_pos_container"))),
                shiny::column(6,
                  shiny::tags$div(class = "card",
                    shiny::tags$div(class = "card-title", "Negative regulon enrichment"),
                    shiny::helpText(style = "font-size:11px;color:#8099b4;",
                                    "Genes negatively correlated (Cor < 0)"),
                    DT::DTOutput("reg_enrich_neg_table"),
                    shiny::uiOutput("reg_enrich_neg_container")))
              )
            )
          )
        )

      ) # tabsetPanel
    )   # nav-wrapper
  )     # fluidPage
}
