# ============================================================
# ui.R — UI builder for SeuratAtlasExplorer
# ============================================================

#' Build the Shiny UI for the Atlas Explorer
#'
#' @param metadata_choices Character vector of metadata column names.
#' @return A Shiny UI definition (\code{fluidPage}).
#' @keywords internal
atlas_ui <- function(metadata_choices) {

  tab_label <- function(icon_char, text) {
    shiny::HTML(paste0('<span class="tab-icon">', icon_char, "</span>", text))
  }

  shiny::fluidPage(
    shiny::tags$head(
      shiny::tags$style(shiny::HTML(app_css()))
    ),

    # ---- App header ----
    shiny::tags$div(class = "app-header",
      shiny::tags$span(class = "app-icon", "\U0001F9EC"),
      shiny::tags$div(
        shiny::tags$h1("Seurat Atlas Explorer"),
        shiny::tags$p(class = "app-subtitle",
                      "Single-cell RNA-seq analysis \u00b7 Interactive dashboard")
      )
    ),

    # ---- Tab wrapper ----
    shiny::tags$div(class = "nav-wrapper",
      shiny::tabsetPanel(id = "main_tabs",

        # ============================================================
        # TAB 0 — About
        # ============================================================
        shiny::tabPanel(tab_label("\u2139\uFE0F", "About"),
          shiny::tags$div(style = "max-width:1140px;margin:0 auto;padding:22px 12px 0;",

            shiny::tags$div(class = "info-hero",
              shiny::tags$span(class = "hero-badge",
                               "Bioinformatics \u00b7 scRNA-seq \u00b7 Single-cell Atlas"),
              shiny::tags$h2("Welcome to Seurat Atlas Explorer"),
              shiny::tags$p(
                "A modular, interactive dashboard for the in-depth exploration of single-cell ",
                "RNA-seq atlases \u2014 from UMAP visualisation and differential expression to ",
                "transcription factor regulon analysis and co-expression networks. ",
                "All computations run live on the Seurat object passed to ",
                shiny::tags$code("launch_explorer()"), "."
              )
            ),

            shiny::tags$div(class = "info-tip",
              shiny::tags$strong("How to use: "),
              "Select any tab from the navigation bar above. Choose your parameters in the ",
              "left-hand sidebar and press the action button. All results appear in the main ",
              "panel and can be downloaded as PNG or CSV."
            ),

            shiny::tags$div(class = "dataset-block",
              shiny::tags$h3("\U0001F4C2 About this dataset"),
              shiny::tags$p(
                "This atlas was generated by the ", shiny::tags$strong("Goriely Lab"),
                " and comprises single-cell transcriptomic profiles spanning multiple ",
                "cell populations and tissue compartments. Cells were sequenced using ",
                "10x Genomics Chromium technology, aligned with Cell Ranger, and processed ",
                "in Seurat with Harmony-based batch correction for cross-sample integration."
              ),
              shiny::tags$p(
                "Dimensionality reduction was performed via PCA followed by UMAP on the ",
                "Harmony-corrected embedding (", shiny::tags$code("umap.harmony"),
                "). Cell-type annotation was carried out at multiple resolution levels ",
                "(Population_level1\u20133). Transcription factor activity was inferred using a ",
                "GRN approach, and co-expression modules were identified with hdWGCNA."
              ),
              shiny::tags$div(class = "ds-meta",
                lapply(c("10x Genomics Chromium", "Harmony integration",
                         "Multi-level annotation", "TF regulon analysis",
                         "hdWGCNA modules", "EnrichR pathway analysis"),
                       function(t) shiny::tags$span(class = "ds-tag", t))
              )
            ),

            shiny::tags$div(class = "feature-grid",
              .feature_card("\U0001F5FA\uFE0F", "UMAP + Expression", list(
                "UMAP coloured by any metadata column",
                "FeaturePlot, VlnPlot, DotPlot, DoHeatmap",
                "Blend mode: co-expression of two genes",
                "Split violin / feature plot by any metadata",
                "Top marker genes per cluster (FindMarkers)",
                "Adjustable display size, font and DPI")),
              .feature_card("\U0001F52C", "DEGs + Volcano + Enrichment", list(
                "Subset cells by any metadata value",
                "FindMarkers between any two groups",
                "Interactive volcano with ggrepel labels",
                "p-value and log2FC threshold sliders",
                "Enrichment run separately via EnrichR",
                "Full geneset tables, UP and DOWN CSVs")),
              .feature_card("\U0001F578\uFE0F", "TF Interaction Network", list(
                "Interactive drag-and-zoom visNetwork graph",
                "5 layout algorithms to choose from",
                "Filter by Gain threshold and top N targets",
                "Reverse search: find TFs regulating a gene",
                "TF\u2013TF only interaction mode",
                "Full DB or filtered network CSV download")),
              .feature_card("\U0001F517", "Co-expression Modules", list(
                "hdWGCNA hub gene tables (ranked by kME)",
                "Module size overview table",
                "Gene \u2192 Module lookup by gene name",
                "Per-module pathway enrichment (EnrichR)",
                "Sortable, filterable, paginated tables")),
              .feature_card("\U0001F525", "TF Regulon Heatmap", list(
                "Dot heatmap: TF expression vs regulon activity",
                "Side-by-side positive and negative regulons",
                "Filter by module membership or manual TF list",
                "Per-TF EnrichR enrichment (pos & neg)",
                "PNG heatmap and data CSV download")),
              .feature_card("\u2699\uFE0F", "Universal plot controls", list(
                "Per-plot pixel size sliders for display",
                "Separate inch + DPI controls for download",
                "Font / label size slider on every plot",
                "All tables: sortable, filterable, paginated",
                "All results: PNG and CSV download buttons"))
            ),

            shiny::tags$div(class = "card",
              shiny::tags$div(class = "card-title", "\U0001F4E6 Required R packages"),
              shiny::tags$div(class = "tech-pills",
                lapply(c("Seurat","ggplot2","dplyr","tidyr","plotly","DT",
                         "enrichR","patchwork","ggrepel","visNetwork",
                         "scales","stringr","tibble","hdWGCNA"),
                       function(p) shiny::tags$span(class = "tech-pill", p))
              )
            ),

            shiny::tags$div(class = "info-footer",
              shiny::tags$div(class = "footer-credit",
                shiny::tags$strong("Goriely Lab"), shiny::tags$br(),
                "MRC Weatherall Institute of Molecular Medicine \u00b7 University of Oxford",
                shiny::tags$br(),
                shiny::tags$span(style = "font-size:12px;color:#6b7f96;",
                  "Dataset and analysis pipeline developed by the Goriely Lab. ",
                  "This dashboard was built for internal exploratory use.")
              ),
              shiny::tags$span(class = "footer-badge", "Goriely Lab \u00b7 Oxford")
            ),
            shiny::tags$div(style = "height:30px;")
          )
        ),

        # ============================================================
        # TAB 1 — UMAP + Expression
        # ============================================================
        shiny::tabPanel(tab_label("\U0001F5FA\uFE0F", "UMAP"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("UMAP"),
              shiny::selectInput("umap_groupby", "Group by:",
                choices  = metadata_choices,
                selected = if ("Population_level3" %in% metadata_choices)
                  "Population_level3" else metadata_choices[1]),
              shiny::uiOutput("cluster_selector"),
              shiny::h4("Expression"),
              shiny::textInput("feature",  "Gene / Feature:", value = "MS4A1"),
              shiny::textInput("feature2", "Gene 2 (blend \u00b7 heatmap \u00b7 dot):", value = "CD3D"),
              shiny::radioButtons("plot_type", "Plot type:",
                choices = c("FeaturePlot" = "feature", "VlnPlot" = "vln",
                            "DotPlot" = "dot", "Heatmap" = "heatmap")),
              shiny::conditionalPanel("input.plot_type == 'feature'",
                shiny::checkboxInput("blend_mode", "Blend two genes (co-expression)", FALSE)),
              shiny::conditionalPanel("input.plot_type == 'feature' || input.plot_type == 'vln'",
                shiny::checkboxInput("use_split", "Split by metadata", FALSE),
                shiny::conditionalPanel("input.use_split",
                  shiny::selectInput("split_by", "Split by:", choices = metadata_choices,
                    selected = if (length(metadata_choices) > 1) metadata_choices[2]
                               else metadata_choices[1]))),
              shiny::h4("Marker genes"),
              shiny::sliderInput("n_markers", "Top markers:", min = 5, max = 100, value = 20),
              shiny::actionButton("markers", "Compute markers", icon = shiny::icon("dna"), class = "btn-primary"),
              shiny::h4("Plot controls"),
              plot_size_controls("umap", default_w = 720, default_h = 500),
              plot_size_controls("expr", default_w = 720, default_h = 500),
              shiny::hr(),
              shiny::h5("Downloads"),
              shiny::downloadButton("download_umap",      "UMAP PNG"),
              shiny::downloadButton("download_expr_plot", "Expression PNG"),
              shiny::downloadButton("download_markers",   "Markers CSV")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "\U0001F5FA\uFE0F UMAP"),
                shiny::uiOutput("umap_container")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "\U0001F4CA Expression plot"),
                shiny::uiOutput("expr_container")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "\U0001F3F7\uFE0F Marker genes"),
                DT::DTOutput("marker_table"))
            )
          )
        ),

        # ============================================================
        # TAB 2 — DEGs
        # ============================================================
        shiny::tabPanel(tab_label("\U0001F52C", "DEGs"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Subset & compare"),
              shiny::selectInput("deg_subset_meta", "Subset by:", choices = metadata_choices,
                selected = if ("Population_level3" %in% metadata_choices) "Population_level3" else metadata_choices[1]),
              shiny::uiOutput("deg_subset_value_selector"),
              shiny::hr(),
              shiny::selectInput("deg_compare_meta", "Compare groups from:", choices = metadata_choices,
                selected = if ("tissue" %in% metadata_choices) "tissue" else metadata_choices[1]),
              shiny::uiOutput("deg_group1_selector"),
              shiny::uiOutput("deg_group2_selector"),
              shiny::h4("Thresholds"),
              shiny::sliderInput("pval_cut",    "Adj p-value cutoff:", min = 0.0001, max = 0.1,  value = 0.05),
              shiny::sliderInput("lfc_cut",     "|log2FC| cutoff:",    min = 0,      max = 5,    value = 0, step = 0.1),
              shiny::sliderInput("n_label",     "Volcano labels:",     min = 0,      max = 30,   value = 10),
              shiny::sliderInput("n_deg_table", "Rows in DEG table:",  min = 10,     max = 500,  value = 100),
              shiny::actionButton("deg", "Run DEG analysis", icon = shiny::icon("calculator"), class = "btn-primary"),
              shiny::h4("Enrichment"),
              shiny::selectInput("enrich_db", "EnrichR database:",
                choices = c("GO_Biological_Process_2023","GO_Molecular_Function_2023",
                            "KEGG_2021_Human","Reactome_2022")),
              shiny::sliderInput("n_enrich", "Top terms:", min = 5, max = 30, value = 15),
              shiny::actionButton("run_enrich", "Run Enrichment", icon = shiny::icon("chart-bar"), class = "btn-success"),
              shiny::h4("Plot controls"),
              plot_size_controls("volcano", default_w = 720, default_h = 540),
              plot_size_controls("enrich",  default_w = 720, default_h = 380),
              shiny::hr(), shiny::h5("Downloads"),
              shiny::downloadButton("download_degs",            "DEGs CSV"),
              shiny::downloadButton("download_volcano",         "Volcano PNG"),
              shiny::downloadButton("download_enrich_up",       "UP enrichment PNG"),
              shiny::downloadButton("download_enrich_down",     "DOWN enrichment PNG"),
              shiny::downloadButton("download_enrich_up_csv",   "UP enrichment CSV"),
              shiny::downloadButton("download_enrich_down_csv", "DOWN enrichment CSV")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "\U0001F4CB DEG results"),
                DT::DTOutput("deg_table")),
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "\U0001F30B Volcano plot"),
                shiny::uiOutput("volcano_container")),
              shiny::fluidRow(
                shiny::column(6, shiny::tags$div(class = "card",
                  shiny::tags$div(class = "card-title", "\u2B06\uFE0F UP-regulated enrichment"),
                  shiny::plotOutput("enrich_up_plot"), shiny::hr(),
                  shiny::h5(style="font-size:13px;color:#1a2e45;margin-top:10px;","Geneset table"),
                  DT::DTOutput("enrich_up_table"))),
                shiny::column(6, shiny::tags$div(class = "card",
                  shiny::tags$div(class = "card-title", "\u2B07\uFE0F DOWN-regulated enrichment"),
                  shiny::plotOutput("enrich_down_plot"), shiny::hr(),
                  shiny::h5(style="font-size:13px;color:#1a2e45;margin-top:10px;","Geneset table"),
                  DT::DTOutput("enrich_down_table")))
              )
            )
          )
        ),

        # ============================================================
        # TAB 3 — TF Network
        # ============================================================
        shiny::tabPanel(tab_label("\U0001F578\uFE0F", "TF Network"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Source TF"),
              shiny::textInput("tf_center", "TF (source):", "MAFB"),
              shiny::h4("Reverse search"),
              shiny::textInput("tf_target_search", "Find TFs regulating gene:", ""),
              shiny::h4("Filters"),
              shiny::sliderInput("min_gain",      "Min Gain:",      min=0, max=1, value=0.05, step=0.01),
              shiny::sliderInput("n_top_targets", "Top N targets:", min=5, max=200, value=50),
              shiny::radioButtons("target_level", "Depth:", choices=c("1-step"=1,"2-step"=2)),
              shiny::checkboxInput("tf_tf_only", "Show only TF\u2013TF interactions", FALSE),
              shiny::h4("Layout"),
              shiny::selectInput("network_layout", "Algorithm:",
                choices = c("Fruchterman-Reingold"="fr","Kamada-Kawai"="kk",
                            "Large graph (DrL)"="drl","Circle"="circle","Nicely"="nicely")),
              shiny::actionButton("update_network", "Update network",
                                  icon = shiny::icon("rotate"), class = "btn-primary"),
              shiny::hr(), shiny::h5("Downloads"),
              shiny::downloadButton("download_network_full",     "Full interaction DB (CSV)"),
              shiny::downloadButton("download_network_filtered", "Filtered network (CSV)")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class = "card",
                shiny::tags$div(class = "card-title", "\U0001F578\uFE0F TF Interaction Network",
                  shiny::tags$span(style="font-size:11px;color:#8099b4;font-weight:400;margin-left:8px;",
                    "\U0001F535 TF node \u00b7 \u26AB Target gene \u00b7 \U0001F534 Center/query \u00b7 Blue edge = positive \u00b7 Red edge = negative")),
                visNetwork::visNetworkOutput("network_plot", height = "680px"))
            )
          )
        ),

        # ============================================================
        # TAB 4 — Co-expression Modules
        # ============================================================
        shiny::tabPanel(tab_label("\U0001F517", "Modules"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Hub genes"),
              shiny::sliderInput("coexp_n_hubs","Top hub genes per module:", min=5, max=50, value=10),
              shiny::actionButton("run_coexp","Load modules", icon=shiny::icon("dna"), class="btn-primary"),
              shiny::downloadButton("download_hub_genes","Hub genes CSV"),
              shiny::h4("Gene lookup"),
              shiny::textInput("gene_lookup","Gene name:",""),
              shiny::actionButton("run_gene_lookup","Find module", icon=shiny::icon("search"), class="btn-primary"),
              shiny::h4("Module enrichment"),
              shiny::uiOutput("coexp_module_selector"),
              shiny::selectInput("coexp_enrich_db","EnrichR database:",
                choices=c("GO_Biological_Process_2023","GO_Molecular_Function_2023",
                          "KEGG_2021_Human","Reactome_2022")),
              shiny::sliderInput("coexp_n_enrich","Top terms:", min=5, max=30, value=10),
              shiny::actionButton("run_coexp_enrich","Run enrichment",icon=shiny::icon("chart-bar"),class="btn-success"),
              shiny::h4("Plot controls"),
              plot_size_controls("coexp_enrich", default_w=720, default_h=380),
              shiny::hr(),
              shiny::downloadButton("download_coexp_enrich",     "Enrichment CSV"),
              shiny::downloadButton("download_coexp_enrich_plot","Barplot PNG")
            ),
            shiny::mainPanel(width = 9,
              shiny::fluidRow(
                shiny::column(5, shiny::tags$div(class="card",
                  shiny::tags$div(class="card-title","\U0001F4CF Module sizes"),
                  DT::DTOutput("module_size_table"))),
                shiny::column(7, shiny::tags$div(class="card",
                  shiny::tags$div(class="card-title","\U0001F50D Gene \u2192 Module lookup"),
                  shiny::verbatimTextOutput("gene_lookup_result")))
              ),
              shiny::tags$div(class="card",
                shiny::tags$div(class="card-title","\u2B50 Hub genes per module"),
                DT::DTOutput("hub_genes_table")),
              shiny::tags$div(class="card",
                shiny::tags$div(class="card-title","\U0001F4CA",shiny::textOutput("enrich_module_title",inline=TRUE)),
                shiny::uiOutput("coexp_enrich_container"), shiny::hr(),
                DT::DTOutput("coexp_enrich_table"))
            )
          )
        ),

        # ============================================================
        # TAB 5 — TF Regulon Heatmap
        # ============================================================
        shiny::tabPanel(tab_label("\U0001F525", "Regulon"),
          shiny::sidebarLayout(
            shiny::sidebarPanel(width = 3,
              shiny::h4("Heatmap settings"),
              shiny::h5("Module filter"),
              shiny::uiOutput("reg_module_selector"),
              shiny::helpText("Leave 'All modules' to show all TFs."),
              shiny::h5("Network filters"),
              shiny::sliderInput("reg_min_gain","Min Gain:", min=0, max=1, value=0.05, step=0.01),
              shiny::sliderInput("reg_min_regulon_size","Min regulon size (pos/neg):", min=1, max=50, value=5),
              shiny::h5("Display"),
              shiny::sliderInput("reg_top_n_tfs","Top N TFs (by regulon size):", min=5, max=100, value=30),
              shiny::textInput("reg_tf_filter","Manual TF filter (comma-sep):",""),
              shiny::sliderInput("reg_dot_range","Dot size range:", min=0.5, max=10, value=c(1,7), step=0.5),
              shiny::actionButton("run_reg_heatmap","Build heatmap",icon=shiny::icon("fire"),class="btn-primary"),
              shiny::h4("Plot controls"),
              plot_size_controls("reg", default_w=820, default_h=880),
              shiny::br(),
              shiny::downloadButton("download_reg_plot","Heatmap PNG"),
              shiny::downloadButton("download_reg_csv", "Data CSV"),
              shiny::h4("TF Regulon Enrichment"),
              shiny::helpText("Build the heatmap first, then select a TF."),
              shiny::uiOutput("reg_enrich_tf_selector"),
              shiny::selectInput("reg_enrich_db","Database:",
                choices=c("GO_Biological_Process_2023","GO_Molecular_Function_2023",
                          "KEGG_2021_Human","Reactome_2022")),
              shiny::sliderInput("reg_enrich_n","Top terms:", min=5, max=30, value=10),
              shiny::actionButton("run_reg_enrich","Run enrichment",icon=shiny::icon("magnifying-glass"),class="btn-success"),
              shiny::h4("Enrichment plot controls"),
              plot_size_controls("reg_enrich", default_w=720, default_h=430),
              shiny::br(),
              shiny::downloadButton("download_reg_enrich_pos_png","POS enrichment PNG"),
              shiny::downloadButton("download_reg_enrich_neg_png","NEG enrichment PNG"),
              shiny::downloadButton("download_reg_enrich_pos_csv","POS enrichment CSV"),
              shiny::downloadButton("download_reg_enrich_neg_csv","NEG enrichment CSV")
            ),
            shiny::mainPanel(width = 9,
              shiny::tags$div(class="card",
                shiny::tags$div(class="card-title","\U0001F525 Regulon dot heatmap"),
                shiny::textOutput("reg_status"), shiny::br(),
                shiny::uiOutput("reg_heatmap_container")),
              shiny::tags$div(class="card",
                shiny::tags$div(class="card-title","\U0001F4CB Regulon summary"),
                DT::DTOutput("reg_summary_table")),
              shiny::fluidRow(
                shiny::column(6, shiny::tags$div(class="card",
                  shiny::tags$div(class="card-title","\u2705 Positive regulon enrichment"),
                  shiny::helpText(style="font-size:11px;color:#8099b4;","Genes positively correlated (Cor > 0)"),
                  DT::DTOutput("reg_enrich_pos_table"),
                  shiny::uiOutput("reg_enrich_pos_container"))),
                shiny::column(6, shiny::tags$div(class="card",
                  shiny::tags$div(class="card-title","\U0001F53B Negative regulon enrichment"),
                  shiny::helpText(style="font-size:11px;color:#8099b4;","Genes negatively correlated (Cor < 0)"),
                  DT::DTOutput("reg_enrich_neg_table"),
                  shiny::uiOutput("reg_enrich_neg_container")))
              )
            )
          )
        )
      ) # tabsetPanel
    )   # nav-wrapper
  )     # fluidPage
}

# ---- Internal helper: feature card for the About page ----
.feature_card <- function(icon, title, items) {
  shiny::tags$div(class = "feature-card",
    shiny::tags$div(class = "fc-icon", icon),
    shiny::tags$h3(title),
    shiny::tags$ul(lapply(items, function(i) shiny::tags$li(i)))
  )
}
